#ifndef INCLUDE_MCAL_GBI_GPI_CONFIGURATION_H_
#define INCLUDE_MCAL_GBI_GPI_CONFIGURATION_H_


/* options:- GPI_u8_ENABLE, GPI_u8_DISABLE */
#define GPI_u8_MODE     GPI_u8_ENABLE

#endif /* INCLUDE_MCAL_GBI_GPI_CONFIGURATION_H_ */
